import { enUS } from "@clerk/localizations";

export const ltLT: typeof enUS = {
  ...enUS,
  locale: "lt-LT",

  formButtonPrimary: "Tęsti",
  formButtonPrimary__verify: "Patvirtinti",
  dividerText: "arba",
  signInEnterPasswordTitle: "Įveskite slaptažodį",

  formFieldLabel__emailAddress: "El. pašto adresas",
  formFieldLabel__emailAddress_username: "El. paštas arba vartotojo vardas",
  formFieldLabel__password: "Slaptažodis",
  formFieldLabel__newPassword: "Naujas slaptažodis",
  formFieldLabel__confirmPassword: "Pakartokite slaptažodį",
  formFieldLabel__currentPassword: "Dabartinis slaptažodis",
  formFieldLabel__firstName: "Vardas",
  formFieldLabel__lastName: "Pavardė",
  formFieldLabel__username: "Vartotojo vardas",
  formFieldLabel__phoneNumber: "Telefono numeris",
  formFieldLabel__backupCode: "Atsarginis kodas",
  formFieldLabel__organizationName: "Organizacijos pavadinimas",
  formFieldLabel__organizationSlug: "Organizacijos URL",
  formFieldLabel__signOutOfOtherSessions: "Atsijungti iš visų kitų įrenginių",
  formFieldLabel__role: "Vaidmuo",
  formFieldLabel__confirmDeletion: "Patvirtinimas",
  formFieldLabel__emailAddresses: "El. pašto adresai",

  formFieldAction__forgotPassword: "Pamiršote slaptažodį?",

  formFieldError__matchingPasswords: "Slaptažodžiai sutampa.",
  formFieldError__notMatchingPasswords: "Slaptažodžiai nesutampa.",
  formFieldError__verificationLinkExpired: "Patvirtinimo nuoroda baigė galioti. Prašome paprašyti naujos.",

  formFieldHintText__optional: "Neprivaloma",
  formFieldHintText__slug: "Naudojamas URL. Gali būti tik mažosios raidės, skaičiai ir brūkšneliai.",

  formFieldInputPlaceholder__emailAddress: "",
  formFieldInputPlaceholder__emailAddress_username: "",
  formFieldInputPlaceholder__password: "",
  formFieldInputPlaceholder__signUpPassword: "",
  formFieldInputPlaceholder__firstName: "",
  formFieldInputPlaceholder__lastName: "",
  formFieldInputPlaceholder__username: "",
  formFieldInputPlaceholder__phoneNumber: "",
  formFieldInputPlaceholder__backupCode: "",
  formFieldInputPlaceholder__organizationName: "",
  formFieldInputPlaceholder__organizationSlug: "",

  badge__default: "Numatytasis",
  badge__primary: "Pagrindinis",
  badge__unverified: "Nepatvirtintas",
  badge__thisDevice: "Šis įrenginys",
  badge__userDevice: "Vartotojo įrenginys",
  badge__otherImpersonatorDevice: "Kitas įrenginys",
  badge__you: "Jūs",

  footerActionLink__alternativePhoneCodeProvider: "Naudoti kitą metodą",
  footerActionLink__useAnotherMethod: "Naudoti kitą metodą",
  footerPageLink__help: "Pagalba",
  footerPageLink__privacy: "Privatumas",
  footerPageLink__terms: "Naudojimo sąlygos",

  backButton: "Atgal",

  signIn: {
    ...enUS.signIn,
    start: {
      ...enUS.signIn.start,
      title: "Prisijungti prie {{applicationName}}",
      subtitle: "Sveikiname sugrįžus! Prašome prisijungti.",
      actionText: "Neturite paskyros?",
      actionLink: "Registruotis",
      actionLink__use_email: "Naudoti el. paštą",
      actionLink__use_email_username: "Naudoti el. paštą arba vartotojo vardą",
      actionLink__use_phone: "Naudoti telefoną",
      actionLink__use_username: "Naudoti vartotojo vardą",
      actionLink__use_passkey: "Naudoti prieigos raktą",
    },
    password: {
      ...enUS.signIn.password,
      title: "Įveskite slaptažodį",
      subtitle: "Įveskite su paskyra susietą slaptažodį",
      actionLink: "Naudoti kitą metodą",
    },
    emailCode: {
      ...enUS.signIn.emailCode,
      title: "Patikrinkite el. paštą",
      subtitle: "norėdami tęsti į {{applicationName}}",
      formTitle: "Patvirtinimo kodas",
      resendButton: "Negavote kodo? Siųsti iš naujo",
    },
    emailLink: {
      ...enUS.signIn.emailLink,
      title: "Patikrinkite el. paštą",
      subtitle: "norėdami tęsti į {{applicationName}}",
      formTitle: "Patvirtinimo nuoroda",
      formSubtitle: "Naudokite patvirtinimo nuorodą, išsiųstą el. paštu",
      resendButton: "Negavote nuorodos? Siųsti iš naujo",
      loading: { subtitle: "Netrukus būsite nukreipti", title: "Prisijungiama..." },
      verified: { subtitle: "Netrukus būsite nukreipti", title: "Prisijungta sėkmingai" },
      verifiedSwitchTab: {
        subtitle: "Grįžkite į pradinį skirtuką tęsti",
        subtitleNewTab: "Grįžkite į naujai atidarytą skirtuką tęsti",
        titleNewTab: "Prisijungta kitame skirtuke",
      },
      expired: { subtitle: "Grįžkite į pradinį skirtuką tęsti.", title: "Patvirtinimo nuoroda baigė galioti" },
      failed: { subtitle: "Grįžkite į pradinį skirtuką tęsti.", title: "Patvirtinimo nuoroda negalioja" },
      unusedTab: { title: "Galite uždaryti šį skirtuką" },
      clientMismatch: {
        subtitle: "Norėdami tęsti, atidarykite patvirtinimo nuorodą iš to paties įrenginio ir naršyklės",
        title: "Patvirtinimo nuoroda negalioja šiam įrenginiui",
      },
    },
    phoneCode: {
      ...enUS.signIn.phoneCode,
      title: "Patikrinkite telefoną",
      subtitle: "norėdami tęsti į {{applicationName}}",
      formTitle: "Patvirtinimo kodas",
      resendButton: "Negavote kodo? Siųsti iš naujo",
    },
    phoneCodeMfa: {
      ...enUS.signIn.phoneCodeMfa,
      title: "Patikrinkite telefoną",
      formTitle: "Patvirtinimo kodas",
      resendButton: "Negavote kodo? Siųsti iš naujo",
      subtitle: "Norėdami tęsti, įveskite patvirtinimo kodą, išsiųstą į jūsų telefoną",
    },
    emailCodeMfa: {
      ...enUS.signIn.emailCodeMfa,
      title: "Patikrinkite el. paštą",
      formTitle: "Patikrinkite el. paštą",
      resendButton: "Negavote kodo? Siųsti iš naujo",
      subtitle: "norėdami tęsti į {{applicationName}}",
    },
    totpMfa: {
      ...enUS.signIn.totpMfa,
      title: "Dviejų žingsnių patvirtinimas",
      formTitle: "Patvirtinimo kodas",
      subtitle: "Norėdami tęsti, įveskite patvirtinimo kodą iš autentifikatoriaus programėlės",
    },
    backupCodeMfa: {
      ...enUS.signIn.backupCodeMfa,
      title: "Įveskite atsarginį kodą",
      subtitle: "Atsarginis kodas buvo suteiktas konfigūruojant dviejų žingsnių autentifikaciją.",
    },
    forgotPassword: {
      ...enUS.signIn.forgotPassword,
      title: "Atstatyti slaptažodį",
      subtitle: "slaptažodžio atstatymui",
      subtitle_email: "Pirmiausia įveskite kodą, išsiųstą jūsų el. paštu",
      subtitle_phone: "Pirmiausia įveskite kodą, išsiųstą jūsų telefonu",
      formTitle: "Atstatymo kodas",
      resendButton: "Negavote kodo? Siųsti iš naujo",
    },
    forgotPasswordAlternativeMethods: {
      ...enUS.signIn.forgotPasswordAlternativeMethods,
      title: "Pamiršote slaptažodį?",
      blockButton__resetPassword: "Atstatyti slaptažodį",
      label__alternativeMethods: "Arba prisijunkite kitu būdu",
    },
    resetPassword: {
      ...enUS.signIn.resetPassword,
      title: "Nustatyti naują slaptažodį",
      formButtonPrimary: "Atstatyti slaptažodį",
      successMessage: "Slaptažodis sėkmingai pakeistas. Prisijungiama, palaukite.",
      requiredMessage: "Saugumo sumetimais būtina pakeisti slaptažodį.",
    },
    alternativeMethods: {
      ...enUS.signIn.alternativeMethods,
      title: "Naudoti kitą metodą",
      subtitle: "Kyla problemų? Galite naudoti bet kurį iš šių metodų prisijungimui.",
      actionText: "Negalite naudoti nė vieno?",
      actionLink: "Gauti pagalbą",
      blockButton__emailCode: "El. pašto kodas {{identifier}}",
      blockButton__emailLink: "El. pašto nuoroda {{identifier}}",
      blockButton__phoneCode: "SMS kodas {{identifier}}",
      blockButton__password: "Prisijungti su slaptažodžiu",
      blockButton__backupCode: "Naudoti atsarginį kodą",
      blockButton__totp: "Naudoti autentifikatoriaus programėlę",
      blockButton__passkey: "Prisijungti su prieigos raktu",
      getHelp: {
        title: "Gauti pagalbą",
        blockButton__emailSupport: "El. paštu",
        content: "Jei kyla problemų prisijungiant, parašykite mums ir kuo greičiau padėsime atgauti prieigą.",
      },
    },
    noAvailableMethods: {
      ...enUS.signIn.noAvailableMethods,
      title: "Nepavyksta prisijungti",
      subtitle: "Įvyko klaida",
      message: "Negalima tęsti prisijungimo. Nėra galimų autentifikacijos metodų.",
    },
    passkey: {
      ...enUS.signIn.passkey,
      title: "Naudoti prieigos raktą",
      subtitle: "Prieigos raktu patvirtinama, kad tai esate jūs. Įrenginys gali paprašyti piršto atspaudo, veido ar ekrano užrakto.",
    },
    accountSwitcher: {
      ...enUS.signIn.accountSwitcher,
      title: "Pasirinkite paskyrą",
      subtitle: "Pasirinkite paskyrą, su kuria norite tęsti.",
      action__addAccount: "Pridėti paskyrą",
      action__signOutAll: "Atsijungti iš visų paskyrų",
    },
    newDeviceVerificationNotice: "Prisijungiate iš naujo įrenginio. Prašome patvirtinti tapatybę, kad apsaugotume paskyrą.",
  },

  signUp: {
    ...enUS.signUp,
    start: {
      ...enUS.signUp.start,
      title: "Sukurti paskyrą",
      titleCombined: "Sukurti paskyrą",
      subtitle: "Sveikiname! Prašome užpildyti duomenis.",
      subtitleCombined: "Sveikiname! Prašome užpildyti duomenis.",
      actionText: "Jau turite paskyrą?",
      actionLink: "Prisijungti",
      actionLink__use_email: "Naudoti el. paštą",
      actionLink__use_phone: "Naudoti telefoną",
    },
    continue: {
      ...enUS.signUp.continue,
      title: "Užpildykite trūkstamus laukus",
      subtitle: "Prašome užpildyti likusius duomenis tęsti.",
      actionText: "Jau turite paskyrą?",
      actionLink: "Prisijungti",
    },
    emailCode: {
      ...enUS.signUp.emailCode,
      title: "Patvirtinkite el. paštą",
      subtitle: "Įveskite patvirtinimo kodą, išsiųstą el. paštu",
      formTitle: "Patvirtinimo kodas",
      formSubtitle: "Įveskite patvirtinimo kodą, išsiųstą jūsų el. paštu",
      resendButton: "Negavote kodo? Siųsti iš naujo",
    },
    emailLink: {
      ...enUS.signUp.emailLink,
      title: "Patvirtinkite el. paštą",
      subtitle: "norėdami tęsti į {{applicationName}}",
      formTitle: "Patvirtinimo nuoroda",
      formSubtitle: "Naudokite patvirtinimo nuorodą, išsiųstą jūsų el. paštu",
      resendButton: "Negavote nuorodos? Siųsti iš naujo",
      loading: { title: "Registruojamasi..." },
      verified: { title: "Registracija sėkminga" },
      verifiedSwitchTab: {
        title: "El. paštas sėkmingai patvirtintas",
        subtitle: "Grįžkite į naujai atidarytą skirtuką tęsti",
        subtitleNewTab: "Grįžkite į ankstesnį skirtuką tęsti",
      },
      clientMismatch: {
        title: "Patvirtinimo nuoroda negalioja šiam įrenginiui",
        subtitle: "Norėdami tęsti, atidarykite patvirtinimo nuorodą iš to paties įrenginio ir naršyklės",
      },
    },
    phoneCode: {
      ...enUS.signUp.phoneCode,
      title: "Patvirtinkite telefoną",
      subtitle: "Įveskite patvirtinimo kodą, išsiųstą telefonu",
      formTitle: "Patvirtinimo kodas",
      formSubtitle: "Įveskite patvirtinimo kodą, išsiųstą jūsų telefono numeriu",
      resendButton: "Negavote kodo? Siųsti iš naujo",
    },
    restrictedAccess: {
      ...enUS.signUp.restrictedAccess,
      title: "Prieiga apribota",
      subtitle: "Šiuo metu registracija išjungta. Jei manote, kad turėtumėte turėti prieigą, susisiekite su palaikymu.",
      subtitleWaitlist: "Šiuo metu registracija išjungta. Įsirašykite į laukimo sąrašą, kad sužinotumėte pirmi.",
      actionText: "Jau turite paskyrą?",
      actionLink: "Prisijungti",
      blockButton__emailSupport: "El. paštu",
      blockButton__joinWaitlist: "Prisijungti prie laukimo sąrašo",
    },
  },
};
