import { Router, type IRouter } from "express";
import healthRouter from "./health";
import courtsRouter from "./courts";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import paymentsRouter from "./payments";
import statsRouter from "./stats";
import uploadRouter from "./upload";
import favoritesRouter from "./favorites";
import adminRouter from "./admin";
import blockedSlotsRouter from "./blocked-slots";
import rolesRouter from "./roles";
import coachesRouter from "./coaches";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import courtPhotosRouter from "./court-photos";
import trainersRouter from "./trainers";
import tournamentsRouter from "./tournaments";
import facilitiesRouter from "./facilities";
import sitemapRouter from "./sitemap";

const router: IRouter = Router();

router.use(healthRouter);
router.use(courtsRouter);
router.use(blockedSlotsRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(paymentsRouter);
router.use(statsRouter);
router.use(uploadRouter);
router.use(favoritesRouter);
router.use(adminRouter);
router.use(rolesRouter);
router.use(coachesRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(courtPhotosRouter);
router.use(trainersRouter);
router.use(tournamentsRouter);
router.use(facilitiesRouter);
router.use(sitemapRouter);

export default router;
