import { Router, type IRouter } from "express";
import healthRouter from "./health";
import courtsRouter from "./courts";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import paymentsRouter from "./payments";
import statsRouter from "./stats";
import uploadRouter from "./upload";
import favoritesRouter from "./favorites";
import adminRouter from "./admin";
import blockedSlotsRouter from "./blocked-slots";
import rolesRouter from "./roles";
import coachesRouter from "./coaches";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import courtPhotosRouter from "./court-photos";
import coachPhotosRouter from "./coach-photos";
import tournamentsRouter from "./tournaments";
import gamesRouter from "./games";
import directMessagesRouter from "./direct-messages";
import facilitiesRouter from "./facilities";
import ownerOnboardRouter from "./owner-onboard";
import userProfilesRouter from "./user-profiles";
import notificationSettingsRouter from "./notification-settings";
import sportsRouter from "./sports";
import ratingsRouter from "./ratings";
import membershipsRouter from "./memberships";
import userSearchRouter from "./user-search";
import stripeConnectRouter from "./stripe-connect";
import ownerDashboardRouter from "./owner-dashboard";
import ownerBookingsRouter from "./owner-bookings";
import ownerCourtStatsRouter from "./owner-court-stats";
import deleteUserDataRouter from "./delete-user-data";
import diagnosticRouter from "./diagnostic";
import guestBookingsRouter from "./guest-bookings";
import ownerBusinessInfoRouter from "./owner-business-info";
import splitPaymentsRouter from "./split-payments";
import openMatchesRouter from "./open-matches";
import weatherRouter from "./weather";
import waitlistsRouter from "./waitlists";
import relatedCourtsRouter from "./related-courts";
import coachScheduleRouter from "./coach-schedule";
import coachStripeRouter from "./coach-stripe";
import coachServicesRouter from "./coach-services";
import coachBookingsRouter from "./coach-bookings";
import coachReviewsRouter from "./coach-reviews";
import coachDashboardRouter from "./coach-dashboard";
import platformSettingsRouter from "./platform-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(courtsRouter);
router.use(blockedSlotsRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(paymentsRouter);
router.use(statsRouter);
router.use(uploadRouter);
router.use(favoritesRouter);
router.use(adminRouter);
router.use(rolesRouter);
router.use(coachesRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(courtPhotosRouter);
router.use(coachPhotosRouter);
router.use(tournamentsRouter);
router.use(gamesRouter);
router.use(directMessagesRouter);
router.use(facilitiesRouter);
router.use(ownerOnboardRouter);
router.use(userProfilesRouter);
router.use(notificationSettingsRouter);
router.use(sportsRouter);
router.use(ratingsRouter);
router.use(membershipsRouter);
router.use(userSearchRouter);
router.use(stripeConnectRouter);
router.use(ownerDashboardRouter);
router.use(ownerBookingsRouter);
router.use(ownerCourtStatsRouter);
router.use(deleteUserDataRouter);
router.use(diagnosticRouter);
router.use(guestBookingsRouter);
router.use(ownerBusinessInfoRouter);
router.use(splitPaymentsRouter);
router.use(openMatchesRouter);
router.use(weatherRouter);
router.use(waitlistsRouter);
router.use(relatedCourtsRouter);
router.use(coachScheduleRouter);
router.use(coachStripeRouter);
router.use(coachServicesRouter);
router.use(coachBookingsRouter);
router.use(coachReviewsRouter);
router.use(coachDashboardRouter);
router.use(platformSettingsRouter);

export default router;
